version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building application..."
      - npm run build
      - zip -r backend.zip .

  post_build:
    commands:
      - echo "Preparing backend AMI bake..."
      - chmod +x scripts/bake_ami.sh
      - ./scripts/bake_ami.sh
