version: 0.2

env:
  parameter-store:
    BASE_AMI: /backend/base-ami-id
    SUBNET_ID: /backend/subnet-id
    SG_ID: /backend/security-group-id
    IAM_PROFILE: /backend/iam-profile
    LAUNCH_TEMPLATE: /backend/launch-template
    ASG_NAME: /backend/asg-name

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      
  build:
    commands:
      - echo "Building backend application with TypeScript..."
      - npm run build
      - echo "Verifying build output exists..."
      - if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then echo "ERROR - Build failed - dist/ directory is empty or missing"; exit 1; fi
      - ls -la dist/
      - echo "Removing dev dependencies and keeping only production deps..."
      - rm -rf node_modules
      - npm ci --omit=dev
      - echo "Verifying package.json is valid..."
      - node -e "JSON.parse(require('fs').readFileSync('package.json','utf8'))" || exit 1
      - echo "Creating deployment package..."
      - mkdir -p deploy
      - cp -r dist deploy/
      - cp -r node_modules deploy/
      - cp package.json deploy/
      - cp package-lock.json deploy/
      - echo "Validating deployment package..."
      - cd deploy
      - node -e "JSON.parse(require('fs').readFileSync('package.json','utf8'))" || exit 1
      - test -d dist || (echo "ERROR - dist/ missing in deploy package" && exit 1)
      - test -d node_modules || (echo "ERROR - node_modules missing in deploy package" && exit 1)
      - echo "Creating zip archive..."
      - zip -r ../backend.zip . || exit 1
      - cd ..
      - echo "Verifying zip file integrity..."
      - unzip -t backend.zip || exit 1
      - echo "Uploading backend.zip to S3..."
      - aws s3 cp backend.zip s3://backend-artifacts-2025/backend-${CODEBUILD_BUILD_NUMBER:-$(date +%s)}.zip || exit 1
      - aws s3 cp backend.zip s3://backend-artifacts-2025/backend.zip || exit 1
      - echo "Build artifacts uploaded successfully"
      
  post_build:
    commands:
      - echo "=========================================="
      - echo "Starting backend AMI bake process..."
      - echo "=========================================="
      - echo "Launching temporary EC2 instance..."
      - INSTANCE_ID=$(aws ec2 run-instances --image-id "$BASE_AMI" --instance-type t2.micro --subnet-id "$SUBNET_ID" --security-group-ids "$SG_ID" --iam-instance-profile Name=$IAM_PROFILE --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=backend-bake-temp},{Key=BuildNumber,Value=${CODEBUILD_BUILD_NUMBER:-unknown}}]" --query "Instances[0].InstanceId" --output text)
      - echo "Temporary instance launched - $INSTANCE_ID"
      - echo "Waiting for instance to be running..."
      - aws ec2 wait instance-running --instance-ids "$INSTANCE_ID" || exit 1
      - echo "Instance is running"
      - echo "Waiting for SSM agent to be online (may take 2-3 minutes)..."
      - sleep 45
      - for i in {1..30}; do STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query "InstanceInformationList[0].PingStatus" --output text 2>/dev/null || echo "NotFound"); echo "Attempt $i/30 - SSM Status - $STATUS"; if [ "$STATUS" = "Online" ]; then echo "SSM agent is online!"; break; fi; if [ $i -eq 30 ]; then echo "ERROR - SSM agent did not come online after 5 minutes"; aws ec2 describe-instances --instance-ids "$INSTANCE_ID"; aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" || true; exit 1; fi; sleep 10; done
      - echo "Deploying backend application via SSM..."
      - COMMAND_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters 'commands=["set -e","echo Step 1 - Preparing deployment directory","cd /opt","rm -rf backend_new","mkdir backend_new","cd backend_new","echo Step 2 - Downloading application package","aws s3 cp s3://backend-artifacts-2025/backend.zip . || exit 1","echo Step 3 - Extracting package","unzip -o backend.zip || exit 1","echo Step 4 - Validating package contents","test -f package.json || (echo ERROR - package.json missing && exit 1)","test -d dist || (echo ERROR - dist directory missing && exit 1)","test -d node_modules || (echo ERROR - node_modules missing && exit 1)","node -e \"JSON.parse(require('\''fs'\'').readFileSync('\''package.json'\'','\''utf8'\''))\" || exit 1","echo Step 5 - Installing application","cd /opt","rm -rf backend_old","if [ -d backend ]; then mv backend backend_old; fi","mv backend_new backend","echo Step 6 - Configuring systemd service","sudo systemctl daemon-reload","sudo systemctl enable backend","echo Step 7 - Starting backend service","sudo systemctl restart backend","echo Step 8 - Waiting for service to initialize","sleep 15","echo Step 9 - Checking service status","sudo systemctl is-active backend || (sudo systemctl status backend --no-pager -l && exit 1)","echo Deployment completed successfully"]' --query "Command.CommandId" --output text)
      - echo "SSM command sent with ID - $COMMAND_ID"
      - echo "Waiting for deployment command to complete..."
      - sleep 10
      - for i in {1..36}; do CMD_STATUS=$(aws ssm list-commands --command-id "$COMMAND_ID" --query "Commands[0].Status" --output text 2>/dev/null || echo "Unknown"); echo "Check $i/36 - Command Status - $CMD_STATUS"; if [ "$CMD_STATUS" = "Success" ] || [ "$CMD_STATUS" = "Failed" ] || [ "$CMD_STATUS" = "Cancelled" ] || [ "$CMD_STATUS" = "TimedOut" ]; then break; fi; sleep 10; done
      - echo "Retrieving command output..."
      - aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "[Status,StandardOutputContent,StandardErrorContent]" --output text
      - COMMAND_STATUS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "Status" --output text)
      - echo "Command execution status - $COMMAND_STATUS"
      - if [ "$COMMAND_STATUS" != "Success" ]; then echo "ERROR - SSM deployment command failed"; echo "Full command details:"; aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID"; aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" || true; exit 1; fi
      - echo "Running health checks on deployed application..."
      - HEALTH_CHECK_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters 'commands=["echo Running health check loop...","for i in {1..30}; do echo Attempt $i/30; if curl -f -s -o /dev/null -w \"%{http_code}\" http://localhost:8000/ | grep -q \"200\\|302\"; then echo Health check PASSED; curl -v http://localhost:8000/; exit 0; fi; sleep 2; done","echo Health check FAILED after 60 seconds","sudo systemctl status backend --no-pager -l","sudo journalctl -u backend -n 50 --no-pager","exit 1"]' --query "Command.CommandId" --output text)
      - echo "Health check command ID - $HEALTH_CHECK_ID"
      - sleep 5
      - for i in {1..24}; do HC_STATUS=$(aws ssm list-commands --command-id "$HEALTH_CHECK_ID" --query "Commands[0].Status" --output text 2>/dev/null || echo "Unknown"); echo "Check $i/24 - Health Check Status - $HC_STATUS"; if [ "$HC_STATUS" = "Success" ] || [ "$HC_STATUS" = "Failed" ] || [ "$HC_STATUS" = "Cancelled" ] || [ "$HC_STATUS" = "TimedOut" ]; then break; fi; sleep 5; done
      - HEALTH_STATUS=$(aws ssm get-command-invocation --command-id "$HEALTH_CHECK_ID" --instance-id "$INSTANCE_ID" --query "Status" --output text)
      - echo "Health check status - $HEALTH_STATUS"
      - if [ "$HEALTH_STATUS" != "Success" ]; then echo "ERROR - Health check failed - service is not responding correctly"; echo "Health check output:"; aws ssm get-command-invocation --command-id "$HEALTH_CHECK_ID" --instance-id "$INSTANCE_ID"; aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" || true; exit 1; fi
      - echo "Health checks passed! Application is running correctly."
      - echo "Creating AMI from validated instance..."
      - AMI_ID=$(aws ec2 create-image --instance-id "$INSTANCE_ID" --name "backend-ami-${CODEBUILD_BUILD_NUMBER:-$(date +%s)}-$(date +%Y%m%d-%H%M%S)" --description "Backend AMI - Build ${CODEBUILD_BUILD_NUMBER:-unknown} - $(date -u +%Y-%m-%dT%H:%M:%SZ)" --no-reboot --query ImageId --output text)
      - echo "New AMI created - $AMI_ID"
      - echo "Tagging AMI with metadata..."
      - aws ec2 create-tags --resources "$AMI_ID" --tags "Key=Name,Value=backend-ami-${CODEBUILD_BUILD_NUMBER:-$(date +%s)}" "Key=BuildNumber,Value=${CODEBUILD_BUILD_NUMBER:-unknown}" "Key=CreatedBy,Value=CodeBuild" "Key=BuildDate,Value=$(date -u +%Y-%m-%dT%H:%M:%SZ)" || true
      - echo "Waiting for AMI to be available..."
      - aws ec2 wait image-available --image-ids "$AMI_ID" || exit 1
      - echo "AMI is now available - $AMI_ID"
      - echo "Creating new launch template version..."
      - NEW_VERSION=$(aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE" --source-version '$Latest' --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" --query 'LaunchTemplateVersion.VersionNumber' --output text)
      - echo "New launch template version created - $NEW_VERSION"
      - echo "Setting new launch template version as default..."
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE" --default-version "$NEW_VERSION" || exit 1
      - echo "Configuring Auto Scaling Group..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --health-check-grace-period 300 || exit 1
      - echo "Triggering rolling instance refresh..."
      - REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --strategy Rolling --preferences "MinHealthyPercentage=50,InstanceWarmup=180,CheckpointPercentages=50,CheckpointDelay=300" --query 'InstanceRefreshId' --output text)
      - echo "Instance refresh started - $REFRESH_ID"
      - echo "Cleaning up temporary instance..."
      - aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" || true
      - echo "=========================================="
      - echo "Backend AMI bake completed successfully!"
      - echo "=========================================="
      - echo "AMI ID - $AMI_ID"
      - echo "Launch Template Version - $NEW_VERSION"
      - echo "Instance Refresh ID - $REFRESH_ID"
      - echo "ASG - $ASG_NAME"
      - echo "=========================================="
      - echo "Monitor the instance refresh with this command:"
      - echo "aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME --instance-refresh-ids $REFRESH_ID"
      - echo "=========================================="

artifacts:
  files:
    - backend.zip
  name: backend-build-${CODEBUILD_BUILD_NUMBER}
