version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building backend..."
      - npm run build || echo "No build step"

artifacts:
  files:
    - '**/*'
  discard-paths: no
