version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm ci

  build:
    commands:
      - echo "Building backend"
      - npm run build
      - zip -r backend.zip .

  post_build:
    commands:
      - echo "Starting AMI bake"
      - aws ec2 run-instances \
          --image-id "$BASE_AMI" \
          --instance-type t2.micro \
          --subnet-id "$SUBNET_ID" \
          --security-group-ids "$SG_ID" \
          --iam-instance-profile Name="$IAM_PROFILE" \
          --query "Instances[0].InstanceId" \
          --output text > instance_id.txt

      - INSTANCE_ID=$(cat instance_id.txt)
      - echo "Instance ID: $INSTANCE_ID"

      - aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
      - aws ssm wait instance-online --instance-ids "$INSTANCE_ID"

      - aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name AWS-RunShellScript \
          --parameters commands="[
            'cd /opt/backend',
            'rm -rf *',
            'aws s3 cp s3://your-artifact-bucket/backend.zip .',
            'unzip backend.zip',
            'npm install --omit=dev',
            'npm run build',
            'sudo systemctl restart backend'
          ]"

      - aws ec2 create-image \
          --instance-id "$INSTANCE_ID" \
          --name backend-ami-$(date +%s) \
          --no-reboot \
          --query ImageId \
          --output text > ami_id.txt

      - AMI_ID=$(cat ami_id.txt)
      - echo "New AMI: $AMI_ID"

      - aws ec2 wait image-available --image-ids "$AMI_ID"

      - aws ec2 modify-launch-template \
          --launch-template-name "$LAUNCH_TEMPLATE" \
          --default-version \
          --launch-template-data ImageId="$AMI_ID"

      - aws autoscaling start-instance-refresh \
          --auto-scaling-group-name "$ASG_NAME" \
          --strategy Rolling \
          --preferences MinHealthyPercentage=50

      - aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
