BUILDSPEC LAST WORKING;version: 0.2

env:
  shell: bash
  parameter-store:
    BASE_AMI: /backend/base-ami-id
    SUBNET_ID: /backend/subnet-id
    SG_ID: /backend/security-group-id
    IAM_PROFILE: /backend/iam-profile
    LAUNCH_TEMPLATE: /backend/launch-template
    ASG_NAME: /backend/asg-name

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade awscli jq

  pre_build:
    commands:
      - echo "Setting build variables"
      - BUILD_TS=$(date +%Y%m%d%H%M%S)
      - AMI_NAME="backend-${BUILD_TS}"
      - INSTANCE_TYPE=t2.micro

  build:
    commands:
      - echo "Launching temporary EC2 instance"
      - |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id "$BASE_AMI" \
          --instance-type "$INSTANCE_TYPE" \
          --subnet-id "$SUBNET_ID" \
          --security-group-ids "$SG_ID" \
          --iam-instance-profile Name="$IAM_PROFILE" \
          --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=backend-build-${BUILD_TS}}]" \
          --query 'Instances[0].InstanceId' \
          --output text)

      - echo "Waiting for instance to become ready"
      - aws ec2 wait instance-status-ok --instance-ids "$INSTANCE_ID"

      - echo "Deploying backend code via SSM"
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy backend application" \
          --parameters commands=[
            "cd /opt/backend",
            "git pull origin main",
            "npm install --production",
            "systemctl restart backend"
          ]

      - echo "Creating new AMI"
      - |
        AMI_ID=$(aws ec2 create-image \
          --instance-id "$INSTANCE_ID" \
          --name "$AMI_NAME" \
          --no-reboot \
          --query ImageId \
          --output text)

      - echo "Waiting for AMI to become available"
      - aws ec2 wait image-available --image-ids "$AMI_ID"

  post_build:
    commands:
      - echo "Creating new Launch Template version"
      - |
        LT_VERSION=$(aws ec2 create-launch-template-version \
          --launch-template-name "$LAUNCH_TEMPLATE" \
          --source-version '$Latest' \
          --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" \
          --query 'LaunchTemplateVersion.VersionNumber' \
          --output text)

      - echo "Updating ASG to use new Launch Template version"
      - |
        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name "$ASG_NAME" \
          --launch-template LaunchTemplateName="$LAUNCH_TEMPLATE",Version="$LT_VERSION"

      - echo "Starting rolling instance refresh"
      - |
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name "$ASG_NAME" \
          --strategy Rolling \
          --preferences MinHealthyPercentage=90,InstanceWarmup=300

      - echo "Terminating temporary build instance"
      - aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
