version: 0.2

env:
  parameter-store:
    BASE_AMI: /backend/base-ami-id
    SUBNET_ID: /backend/subnet-id
    SG_ID: /backend/security-group-id
    IAM_PROFILE: /backend/iam-profile
    LAUNCH_TEMPLATE: /backend/launch-template
    ASG_NAME: /backend/asg-name

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      
  build:
    commands:
      - echo "Building backend application..."
      - npm run build
      - echo "Installing production dependencies..."
      - rm -rf node_modules
      - npm ci --omit=dev
      - echo "Verifying package.json before zipping..."
      - cat package.json
      - wc -c package.json
      - echo "Creating deployment package..."
      - zip -r backend.zip dist/ node_modules/ package.json package-lock.json
      - echo "Verifying zip contents..."
      - unzip -l backend.zip | grep package.json
      - unzip -p backend.zip package.json | head -20
      - echo "Uploading to S3..."
      - aws s3 cp backend.zip s3://backend-artifacts-2025/backend.zip
      - echo "Verifying S3 upload..."
      - aws s3 ls s3://backend-artifacts-2025/backend.zip --human-readable
      
  post_build:
    commands:
      - echo "Starting backend AMI bake process..."
      - echo "Launching temporary EC2 instance..."
      - INSTANCE_ID=$(aws ec2 run-instances --image-id "$BASE_AMI" --instance-type t2.micro --subnet-id "$SUBNET_ID" --security-group-ids "$SG_ID" --iam-instance-profile Name=$IAM_PROFILE --query "Instances[0].InstanceId" --output text)
      - echo "Temporary instance launched $INSTANCE_ID"
      - aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
      - echo "Waiting for SSM agent..."
      - sleep 30
      - for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query "InstanceInformationList[0].PingStatus" --output text 2>/dev/null || echo "NotFound"); echo "Attempt $i/30 - SSM Status $STATUS"; if [ "$STATUS" = "Online" ]; then echo "SSM agent is online!"; break; fi; if [ $i -eq 30 ]; then echo "ERROR SSM agent did not come online"; exit 1; fi; sleep 10; done
      - echo "Deploying backend via SSM..."
      - COMMAND_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters 'commands=["#!/bin/bash","set -ex","echo \"Stopping backend service\"","sudo systemctl stop backend || true","echo \"Creating temp directory\"","mkdir -p /tmp/backend-deploy","cd /tmp/backend-deploy","echo \"Downloading from S3\"","aws s3 cp s3://backend-artifacts-2025/backend.zip . || exit 1","echo \"Verifying download\"","ls -lh backend.zip","file backend.zip","echo \"Extracting files\"","unzip -o backend.zip || exit 1","echo \"Verifying extracted files\"","ls -la","echo \"Checking package.json\"","cat package.json | head -5 || exit 1","test -s package.json || (echo \"ERROR: package.json is empty\" && exit 1)","echo \"Clearing /opt/backend\"","sudo rm -rf /opt/backend/*","echo \"Moving files to /opt/backend\"","sudo cp -r * /opt/backend/","cd /opt/backend","echo \"Final verification\"","ls -la","cat package.json | jq . || exit 1","echo \"Starting service\"","sudo systemctl daemon-reload","sudo systemctl enable backend","sudo systemctl start backend","sleep 10","sudo systemctl status backend --no-pager","echo \"Testing service\"","curl -f http://localhost:8000/ || curl -f http://localhost:8000/ || echo \"Warning: service not responding\"","echo \"Cleanup\"","rm -rf /tmp/backend-deploy"]' --query "Command.CommandId" --output text)
      - echo "SSM command ID $COMMAND_ID"
      - aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" || true
      - echo "=== SSM Command Output ==="
      - aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "StandardOutputContent" --output text
      - echo "=== SSM Command Errors ==="
      - aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "StandardErrorContent" --output text
      - COMMAND_STATUS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "Status" --output text)
      - echo "Command status $COMMAND_STATUS"
      - if [ "$COMMAND_STATUS" != "Success" ]; then echo "ERROR: Deployment failed"; exit 1; fi
      - echo "Creating AMI..."
      - AMI_ID=$(aws ec2 create-image --instance-id "$INSTANCE_ID" --name "backend-ami-$(date +%s)" --no-reboot --query ImageId --output text)
      - echo "AMI created $AMI_ID"
      - aws ec2 wait image-available --image-ids "$AMI_ID"
      - echo "Updating Launch Template..."
      - NEW_VERSION=$(aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE" --source-version '$Latest' --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" --query 'LaunchTemplateVersion.VersionNumber' --output text)
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE" --default-version "$NEW_VERSION"
      - echo "Updating ASG..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --health-check-grace-period 300
      - aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --strategy Rolling --preferences MinHealthyPercentage=50,InstanceWarmup=120
      - echo "Terminating temp instance..."
      - aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
      - echo "==================================="
      - echo "SUCCESS!"
      - echo "AMI: $AMI_ID"
      - echo "Launch Template Version: $NEW_VERSION"
      - echo "==================================="
