version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Building app..."
      - npm run build
  post_build:
    commands:
      - echo "Packaging artifact..."
      - mkdir -p artifact
      - cp -r dist package.json package-lock.json ecosystem.config.js artifact/
      - cd artifact
      - tar -czf backend-app-1.0.0.tar.gz *
      - aws s3 cp backend-app-1.0.0.tar.gz s3://my-backend-artifacts-123/backend-app-1.0.0.tar.gz
