version: 0.2

env:
  parameter-store:
    BASE_AMI: /backend/base-ami-id
    SUBNET_ID: /backend/subnet-id
    SG_ID: /backend/security-group-id
    IAM_PROFILE: /backend/iam-profile
    LAUNCH_TEMPLATE: /backend/launch-template
    ASG_NAME: /backend/asg-name

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      
  build:
    commands:
      - echo "Building backend application with TypeScript..."
      - npm run build
      - echo "Removing dev dependencies..."
      - rm -rf node_modules
      - npm ci --omit=dev
      - echo "Creating clean deployment structure..."
      - mkdir -p deploy/backend
      - cp -r dist deploy/backend/
      - cp -r node_modules deploy/backend/
      - cp package.json deploy/backend/
      - cp package-lock.json deploy/backend/
      - cd deploy/backend
      - echo "=== Contents of deployment directory ==="
      - ls -la
      - echo "=== Verifying package.json ==="
      - cat package.json | jq '.' || (echo "Invalid JSON in package.json" && exit 1)
      - cd ..
      - echo "Creating zip file..."
      - zip -r ../backend.zip backend/
      - cd ..
      - echo "=== Zip file created ==="
      - ls -lh backend.zip
      - echo "=== Contents of zip ==="
      - unzip -l backend.zip | head -30
      - echo "Uploading backend.zip to S3..."
      - aws s3 cp backend.zip s3://backend-artifacts-2025/backend.zip
      
  post_build:
    commands:
      - echo "Starting backend AMI bake process..."
      - echo "Launching temporary EC2 instance..."
      - INSTANCE_ID=$(aws ec2 run-instances --image-id "$BASE_AMI" --instance-type t2.micro --subnet-id "$SUBNET_ID" --security-group-ids "$SG_ID" --iam-instance-profile Name=$IAM_PROFILE --query "Instances[0].InstanceId" --output text)
      - echo "Temporary instance launched $INSTANCE_ID"
      - echo "Waiting for instance to be running..."
      - aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
      - echo "Instance is running"
      - echo "Waiting for SSM agent to be online..."
      - sleep 30
      - for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query "InstanceInformationList[0].PingStatus" --output text 2>/dev/null || echo "NotFound"); echo "Attempt $i/30 - SSM Status $STATUS"; if [ "$STATUS" = "Online" ]; then echo "SSM agent is online!"; break; fi; if [ $i -eq 30 ]; then echo "ERROR SSM agent did not come online"; exit 1; fi; sleep 10; done
      - echo "Deploying backend application via SSM..."
      - COMMAND_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters 'commands=["set -e","echo \"=== Stopping backend service ===\"","sudo systemctl stop backend || true","echo \"=== Cleaning /opt/backend ===\"","sudo rm -rf /opt/backend/*","echo \"=== Downloading from S3 ===\"","cd /opt","aws s3 cp s3://backend-artifacts-2025/backend.zip . --debug","echo \"=== Verifying download ===\"","ls -lh backend.zip","echo \"=== Extracting archive ===\"","unzip -o backend.zip","echo \"=== Verifying extraction ===\"","ls -la backend/","echo \"=== Checking package.json ===\"","cat backend/package.json | head -10","cat backend/package.json | tail -10","wc -l backend/package.json","echo \"=== Moving files to /opt/backend ===\"","sudo mv backend/* /opt/backend/","echo \"=== Final verification ===\"","ls -la /opt/backend/","cat /opt/backend/package.json","echo \"=== Starting service ===\"","sudo systemctl daemon-reload","sudo systemctl enable backend","sudo systemctl start backend","sleep 15","sudo systemctl status backend --no-pager -l","echo \"=== Testing service ===\"","curl -f http://localhost:8000/ || curl -f http://localhost:8000/ || echo \"Service not responding\""]' --query "Command.CommandId" --output text)
      - echo "SSM command sent with ID $COMMAND_ID"
      - echo "Waiting for deployment command to complete..."
      - aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" || true
      - echo "Getting full SSM command output..."
      - aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID"
      - COMMAND_STATUS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "Status" --output text)
      - echo "Command execution status $COMMAND_STATUS"
      - if [ "$COMMAND_STATUS" != "Success" ]; then echo "ERROR SSM command failed - check output above"; exit 1; fi
      - echo "Creating new AMI from configured instance..."
      - AMI_ID=$(aws ec2 create-image --instance-id "$INSTANCE_ID" --name "backend-ami-$(date +%s)" --no-reboot --query ImageId --output text)
      - echo "New AMI created with ID $AMI_ID"
      - aws ec2 wait image-available --image-ids "$AMI_ID"
      - echo "Creating new launch template version..."
      - NEW_VERSION=$(aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE" --source-version '$Latest' --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" --query 'LaunchTemplateVersion.VersionNumber' --output text)
      - echo "Setting as default version..."
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE" --default-version "$NEW_VERSION"
      - echo "Updating ASG health check grace period..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --health-check-grace-period 300
      - echo "Starting instance refresh..."
      - aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --strategy Rolling --preferences MinHealthyPercentage=50,InstanceWarmup=120
      - echo "Terminating temporary instance..."
      - aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
      - echo "==================================="
      - echo "Deployment completed!"
      - echo "New AMI $AMI_ID"
      - echo "Launch Template Version $NEW_VERSION"
      - echo "==================================="
