version: 0.2

env:
  variables:
    APP_DIR: /opt/backend
    REGION: us-east-1
    ASG_NAME: Backend_ASG
    LAUNCH_TEMPLATE: backend-LT
    BASE_AMI: ami-0b04281af4d9c36f6   # working AMI
    SUBNET_ID: subnet-0554549452d28c3aa
    SG_ID: sg-0aa1c28ac965807f8
    IAM_PROFILE: EC2Roles

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm ci

  build:
    commands:
      - echo "Building application"
      - npm run build
      - zip -r backend.zip .

post_build:
  commands:
    - |
      set -e
      
      echo "Launching temporary EC2 instance..."

      INSTANCE_ID=$(aws ec2 run-instances \
        --image-id "$BASE_AMI" \
        --instance-type t3.micro \
        --subnet-id "$SUBNET_ID" \
        --security-group-ids "$SG_ID" \
        --iam-instance-profile Name="$IAM_PROFILE" \
        --query "Instances[0].InstanceId" \
        --output text)

      echo "Instance ID: $INSTANCE_ID"

      aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"

      echo "Sending SSM commands..."

      aws ssm send-command \
        --instance-ids "$INSTANCE_ID" \
        --document-name "AWS-RunShellScript" \
        --parameters 'commands=[
          "cd /opt/backend",
          "unzip -o /opt/backend/backend.zip",
          "npm install --omit=dev",
          "npm run build",
          "sudo systemctl restart backend"
        ]'

      echo "Creating AMI..."

      AMI_ID=$(aws ec2 create-image \
        --instance-id "$INSTANCE_ID" \
        --name "backend-ami-$(date +%s)" \
        --no-reboot \
        --query "ImageId" \
        --output text)

      aws ec2 wait image-available --image-ids "$AMI_ID"

      echo "Updating launch template..."

      aws ec2 create-launch-template-version \
        --launch-template-name "$LAUNCH_TEMPLATE" \
        --launch-template-data ImageId="$AMI_ID"

      echo "Starting ASG refresh..."

      aws autoscaling start-instance-refresh \
        --auto-scaling-group-name "$ASG_NAME" \
        --strategy Rolling \
        --preferences MinHealthyPercentage=50

      echo "Terminating temp instance..."

      aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
