version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "===== INSTALL PHASE ====="
      - aws --version
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "===== PRE-BUILD PHASE ====="
      - echo "Git commit:"
      - git rev-parse HEAD

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - echo "Nothing to build locally. Build happens on bake EC2."

  post_build:
    commands:
      - |
        set -e

        echo "===== POST-BUILD (AMI BAKING) ====="

        BUILD_ID=$(date +%Y%m%d-%H%M%S)
        echo "BUILD_ID=$BUILD_ID"

        echo "1) Launching temporary EC2 instance..."
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id "$BASE_AMI" \
          --instance-type t3.micro \
          --subnet-id "$SUBNET_ID" \
          --security-group-ids "$SG_ID" \
          --iam-instance-profile Name="$IAM_PROFILE" \
          --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=backend-bake-$BUILD_ID}]" \
          --query "Instances[0].InstanceId" \
          --output text)

        echo "Temporary instance: $INSTANCE_ID"

        echo "2) Waiting for instance to be running..."
        aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"

        echo "3) Waiting for SSM to be ready..."
        aws ssm wait instance-online --instance-ids "$INSTANCE_ID"

        echo "4) Sending build commands via SSM..."
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Bake backend application" \
          --parameters 'commands=[
            "set -e",
            "cd /opt/backend",
            "unzip -o backend.zip",
            "npm install --omit=dev",
            "npm run build",
            "sudo systemctl restart backend"
          ]'

        echo "5) Creating AMI from baked instance..."
        AMI_ID=$(aws ec2 create-image \
          --instance-id "$INSTANCE_ID" \
          --name "backend-ami-$BUILD_ID" \
          --description "Backend AMI built from commit $(git rev-parse HEAD)" \
          --no-reboot \
          --query "ImageId" \
          --output text)

        echo "AMI_ID=$AMI_ID"

        echo "6) Waiting for AMI to become available..."
        aws ec2 wait image-available --image-ids "$AMI_ID"

        echo "7) Creating new Launch Template version..."
        LT_VERSION=$(aws ec2 create-launch-template-version \
          --launch-template-name "$LAUNCH_TEMPLATE" \
          --launch-template-data ImageId="$AMI_ID" \
          --query 'LaunchTemplateVersion.VersionNumber' \
          --output text)

        echo "New Launch Template version: $LT_VERSION"

        echo "8) Setting new Launch Template version as DEFAULT..."
        aws ec2 modify-launch-template \
          --launch-template-name "$LAUNCH_TEMPLATE" \
          --default-version "$LT_VERSION"

        echo "9) Starting Auto Scaling Group instance refresh..."
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name "$ASG_NAME" \
          --strategy Rolling \
          --preferences MinHealthyPercentage=50

        echo "10) Terminating temporary bake instance..."
        aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"

        echo "===== BUILD COMPLETE SUCCESSFULLY ====="
