version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 |
        docker login --username AWS --password-stdin 734649603753.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t backend:latest .
      - docker tag backend:latest 734649603753.dkr.ecr.us-east-1.amazonaws.com/backend:latest
  post_build:
    commands:
      - docker push 734649603753.dkr.ecr.us-east-1.amazonaws.com/backend:latest
