version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm test || true
      - npm run build || true
      - mkdir -p artifact
      - rsync -av --exclude=node_modules --exclude=artifact . artifact/
      - tar -czf backend-app.tar.gz -C artifact .
artifacts:
  files:
    - backend-app.tar.gz
