version: 0.2

phases:
  pre_build:
    commands:
      - set -euxo pipefail
      - aws --version
      - docker --version
      - aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin 734649603753.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Starting Docker build..."
      - docker build --progress=plain -t backend:latest .

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker tag backend:latest 734649603753.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      - docker push 734649603753.dkr.ecr.us-east-1.amazonaws.com/backend:latest
