version: 0.2

env:

  parameter-store:
    BASE_AMI: /backend/base-ami-id
    SUBNET_ID: /backend/subnet-id
    SG_ID: /backend/security-group-id
    IAM_PROFILE: /backend/iam-profile
    LAUNCH_TEMPLATE: /backend/launch-template
    ASG_NAME: /backend/asg-name

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      
  build:
    commands:
      - echo "Building backend application..."
      - npm run build
      - zip -r backend.zip .
      - echo "Uploading backend.zip to S3..."
      - aws s3 cp backend.zip s3://backend-artifacts-2025/backend.zip
      
  post_build:
    commands:
      - echo "Starting backend AMI bake process..."
      - echo "=== DEBUG - Checking environment variables ==="
      - echo "BASE_AMI = $BASE_AMI"
      - echo "SUBNET_ID = $SUBNET_ID"
      - echo "SG_ID = $SG_ID"
      - echo "IAM_PROFILE = $IAM_PROFILE"
      - echo "LAUNCH_TEMPLATE = $LAUNCH_TEMPLATE"
      - echo "ASG_NAME = $ASG_NAME"
      - echo "=== DEBUG - Verifying resources exist ==="
      - aws ec2 describe-images --image-ids "$BASE_AMI" --query "Images[0].[ImageId,Name,State]" --output table || echo "ERROR - BASE_AMI not found or no permission"
      - aws ec2 describe-subnets --subnet-ids "$SUBNET_ID" --query "Subnets[0].[SubnetId,VpcId,AvailabilityZone]" --output table || echo "ERROR - SUBNET_ID not found or no permission"
      - aws ec2 describe-security-groups --group-ids "$SG_ID" --query "SecurityGroups[0].[GroupId,GroupName,VpcId]" --output table || echo "ERROR - SG_ID not found or no permission"
      - aws iam get-instance-profile --instance-profile-name "$IAM_PROFILE" --query "InstanceProfile.[InstanceProfileName,Arn]" --output table || echo "ERROR - IAM_PROFILE not found or no permission"
      - echo "=== DEBUG - Attempting to launch instance ==="
      - aws ec2 run-instances --image-id "$BASE_AMI" --instance-type t2.micro --subnet-id "$SUBNET_ID" --security-group-ids "$SG_ID" --iam-instance-profile Name=$IAM_PROFILE --query "Instances[0].InstanceId" --output text --dry-run || echo "Dry run to check permissions"
      - echo "Launching temporary EC2 instance..."
      - INSTANCE_ID=$(aws ec2 run-instances --image-id "$BASE_AMI" --instance-type t2.micro --subnet-id "$SUBNET_ID" --security-group-ids "$SG_ID" --iam-instance-profile Name=$IAM_PROFILE --query "Instances[0].InstanceId" --output text)
      - echo "Temporary instance launched $INSTANCE_ID"
      - echo "Waiting for instance to be running..."
      - aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
      - echo "Instance is running"
      - echo "Waiting for SSM agent to be online (this may take 2-3 minutes)..."
      - sleep 30
      - for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query "InstanceInformationList[0].PingStatus" --output text 2>/dev/null || echo "NotFound"); echo "Attempt $i/30 - SSM Status $STATUS"; if [ "$STATUS" = "Online" ]; then echo "SSM agent is online!"; break; fi; if [ $i -eq 30 ]; then echo "ERROR SSM agent did not come online"; aws ec2 describe-instances --instance-ids "$INSTANCE_ID"; exit 1; fi; sleep 10; done
      - echo "Deploying backend application via SSM..."
      - COMMAND_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters 'commands=["cd /opt/backend","rm -rf node_modules dist *","aws s3 cp s3://backend-artifacts-2025/backend.zip .","unzip -o backend.zip","npm install --omit=dev","npm install","npm run build","npm prune --production","sudo systemctl daemon-reload","sudo systemctl enable backend","sudo systemctl stop backend"]' --query "Command.CommandId" --output text)
      - echo "SSM command sent with ID $COMMAND_ID"
      - echo "Waiting for deployment command to complete..."
      - aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID"
      - echo "Deployment completed successfully"
      - COMMAND_STATUS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query "Status" --output text)
      - echo "Command execution status $COMMAND_STATUS"
      - if [ "$COMMAND_STATUS" != "Success" ]; then echo "ERROR SSM command failed"; aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID"; exit 1; fi
      - echo "Creating new AMI from configured instance..."
      - AMI_ID=$(aws ec2 create-image --instance-id "$INSTANCE_ID" --name "backend-ami-$(date +%s)" --no-reboot --query ImageId --output text)
      - echo "New AMI created with ID $AMI_ID"
      - echo "Waiting for AMI to be available..."
      - aws ec2 wait image-available --image-ids "$AMI_ID"
      - echo "AMI is now available"
      - echo "Updating Launch Template to use new AMI..."
      - echo "Creating new launch template version..."
      - NEW_VERSION=$(aws ec2 create-launch-template-version --launch-template-name "$LAUNCH_TEMPLATE" --source-version '$Latest' --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" --query 'LaunchTemplateVersion.VersionNumber' --output text)
      - echo "New launch template version $NEW_VERSION created"
      - echo "Setting new launch template version as default..."
      - aws ec2 modify-launch-template --launch-template-name "$LAUNCH_TEMPLATE" --default-version "$NEW_VERSION"
      - echo "Launch Template updated successfully"
      - echo "Setting ASG health check grace period..."
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --health-check-grace-period 180
      - echo "Triggering Auto Scaling Group instance refresh..."
      - aws autoscaling start-instance-refresh --auto-scaling-group-name "$ASG_NAME" --strategy Rolling --preferences MinHealthyPercentage=50,InstanceWarmup=120
      - echo "Instance refresh started"
      - echo "Terminating temporary instance..."
      - aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
      - echo "Temporary instance terminated"
      - echo "==================================="
      - echo "Backend AMI bake completed successfully!"
      - echo "New AMI ID $AMI_ID"
      - echo "ASG will gradually roll out new instances"
      - echo "==================================="
